# Site settings
title: 虾哥哥Blog
SEOTitle: 虾哥哥Blog
header-img: img/home-bg.jpg
email: jfk_jin@sina.com
description: ""
keyword: "KODI, XBMC, jindaxia, JFK, jfk, 金大虾, jfk_jin"
url: "http://jindaxia.github.io"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'



# SNS settings
RSS: false
weibo_username: jin777
# zhihu_username: jindaxia
github_username: jindaxia
twitter_username: jindaxia
# facebook_username:  huxpro



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
plugins: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1


# Disqus settings
#disqus_username: _your_disqus_short_name_

# gitment settings
gitment: false

utterances: true
utterances-repo: jindaxia/jindaxia.github.io


# Analytics settings
# Baidu Analytics
# ba_track_id: 4cc1f2d8f3067386cc5cdb626a202900
# # Google Analytics
# ga_track_id: 'UA-49627206-1'            # Format: UA-xxxxxx-xx
# ga_domain: huangxuan.me



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "我踏破铁鞋 是否就能找到谁。<br/>人常常推开眼前 不顾一切去坠毁。"
sidebar-avatar: /img/avatar-wolf.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value


# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true


# Friends
friends: [
    {
        title: "虾哥哥Blog",
        href: "https://jindaxia.github.io"
    },
]
